// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package webhook

import (
	"github.com/ledboot/OwlHook/api/webhook"
)

type ControllerV1 struct{}

func NewV1() webhook.IWebhookV1 {
	return &ControllerV1{}
}
